services:
  postgres:
    image: postgres:18.1-2.1C-ubuntu2204
    container_name: postgres-1c
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: template1c
      # Русская локаль:
      LANG: ru_RU.UTF-8
      LC_ALL: ru_RU.UTF-8
      LC_COLLATE: ru_RU.UTF-8
      LC_CTYPE: ru_RU.UTF-8    
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - infra-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Добавить в КОНЕЦ секции postgres (на одном уровне с image, container_name и т.д.):
    command: >
      postgres
      -c lc_collate=ru_RU.UTF-8
      -c lc_ctype=ru_RU.UTF-8
      -c lc_messages=ru_RU.UTF-8
      -c lc_monetary=ru_RU.UTF-8
      -c lc_numeric=ru_RU.UTF-8
      -c lc_time=ru_RU.UTF-8

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
#      - "9000:9000"
#      - "8000:8000"
      - "0.0.0.0:9000:9000"  # ← важно! не 127.0.0.1, Portainer
      - "0.0.0.0:8000:8000"  # ← важно! не 127.0.0.1, Portainer
    volumes:
      - //./pipe/docker_engine:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - infra-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
#      - "5050:80"
      - "0.0.0.0:5050:80"    # ← важно! pgAdmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - infra-net
    depends_on:
      - postgres

networks:
  infra-net:
    driver: bridge

volumes:
  postgres-data:
  portainer-data:
  pgadmin-data: